#!/bin/bash

#clean folder
rm -rf dist/*

#build and compile css
npm run build
node-sass --output-style compressed src/styles/main.scss > dist/main.css
node-sass --output-style compressed tesm/styles/main.scss > dist/team/main.css

#copy over html and assets
cp index.html dist
cp team/index.html dist/team
cp -R assets dist
